config/routes.rb
Student::Application.routes.draw do
	resources :studs
	resources :courses
	resources :grades

	root :to => 'studs#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :description, :name, :number

  has_many :grades
  has_many :studs, :through => :grades
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  attr_accessible :course_id, :lettergrade, :stud_id
  belongs_to :stud
  belongs_to :course
end

app/models/stud.rb
class Stud < ActiveRecord::Base
  attr_accessible :grade_id, :name
  
  has_many :grades
  has_many :courses, :through => :grades
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def index
		@courses = Course.all
	end

	def new
		@course = Course.new
	end

	def create
		@course = Course.new(params[:course])
		
		if @course.save
			redirect_to @course, notice: 'Course was successfully created.'
		end		
	end

	def edit
		@course = Course.find(params[:id])		
	end

	def update
		@course = Course.find(params[:id])
		
		if @course.update_attributes(params[:course])
			redirect_to @course, notice: 'Course was successfully updated'
		end
	end

	def destroy
		@course = Course.find(params[:id])
		@course.destroy

		redirect_to courses_path
	end

	def show
		@course = Course.find(params[:id])
	end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
	def index
		@grades = Grade.all
	end

	def new
		@grade = Grade.new
	end

	def create
		@grade = Grade.new(params[:grade])
		
		if @grade.save
			redirect_to @grade, notice: 'Grade was successfully created.'
		end		
	end

	def edit
		@grade = Grade.find(params[:id])		
	end

	def update
		@grade = Grade.find(params[:id])
		
		if @grade.update_attributes(params[:grade])
			redirect_to @grade, notice: 'Grade was successfully updated'
		end
	end

	def destroy
		@grade = Grade.find(params[:id])
		@grade.destroy

		redirect_to grades_path
	end

	def show
		@grade = Grade.find(params[:id])
		@stud = Stud.find(@grade.stud_id)
		@course = Course.find(@grade.course_id)
	end
end

app/controllers/studs_controller.rb
class StudsController < ApplicationController
	def index
		@studs = Stud.all
	end

	def new
		@stud = Stud.new
	end

	def create
		@stud = Stud.new(params[:stud])
		
		if @stud.save
			redirect_to @stud, notice: 'Student was successfully created.'
		end		
	end

	def edit
		@stud = Stud.find(params[:id])		
	end

	def update
		@stud = Stud.find(params[:id])
		
		if @stud.update_attributes(params[:stud])
			redirect_to @stud, notice: 'Student was successfully updated'
		end
	end

	def destroy
		@stud = Stud.find(params[:id])
		@stud.destroy

		redirect_to studs_path
	end

	def show
		@stud = Stud.find(params[:id])
		@grades = Grade.where(:stud_id => @stud.id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/studs_helper.rb
module StudsHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>

<div>
	<%= f.label :number %><br />
	<%= f.text_field :number %>
</div>

<div>
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>

<div>
	<%= f.label :description %><br />
	<%= f.text_field :description %>
</div>

<div>
	<%= f.submit 'Submit' %>
</div>

<% end %>

app/views/courses/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @course %> | 
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<%= link_to 'Create New Course', new_course_path %>

<% @courses.each do |course| %>
<div>
	<%= course.id %> <%= course.number %> <%= course.name %> <%= course.description %>
	<%= link_to 'View', course%>
	<%= link_to 'Edit', edit_course_path(course) %>
	<%= link_to 'Delete', course, confirm: 'Are you sure?', method: :delete %>
</div>

<% end %>

app/views/courses/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<div><%= notice %></div>
<div><b>ID:</b><%= @course.id %></div>
<div><b>Number:</b><%= @course.number %></div>
<div><b>Name:</b><%= @course.name %></div>
<div><b>Description:</b><%= @course.description %></div>

<div>
<%= link_to 'Edit', edit_course_path(@course) %> | 
<%= link_to 'Back', courses_path %>
</div>

app/views/grades/_form.html.erb
<%= form_for(@grade) do |f| %>

<div>
	<%= f.label :lettergrade %><br />
	<%= f.text_field :lettergrade %>
</div>

<div>
<%= f.label :course_id %><br />
<%= collection_select(:grade, :course_id, Course.all, :id, :name) %>
</div>

<div>
<%= f.label :stud_id %><br />
<%= collection_select(:grade, :stud_id, Stud.all, :id, :name) %>
</div>

<div>
	<%= f.submit 'Submit' %>
</div>

<% end %>

app/views/grades/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @grade %> | 
<%= link_to 'Back', grades_path %>

app/views/grades/index.html.erb
<%= link_to 'Create New Grade', new_grade_path %>

<% @grades.each do |grade| %>
<% 
	@stud = grade.stud_id
        @course = grade.course_id
        if @stud
           @studinfo = Stud.find(@stud)
        end
        if @course
           @courseinfo = Course.find(@course)
        end
%>
<div>
	<%= grade.id %> <%= grade.lettergrade %>
	<% if @stud %>
        	<%= @studinfo.name %>
        <% end %>
	<% if @course %>
        	<%= @courseinfo.name %>
        <% end %>
	<%= link_to 'View', grade%>
	<%= link_to 'Edit', edit_grade_path(grade) %>
	<%= link_to 'Delete', grade, confirm: 'Are you sure?', method: :delete %>
</div>

<% end %>

app/views/grades/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', grades_path %>

app/views/grades/show.html.erb
<div><%= notice %></div>
<div><b>Student:</b><%= @stud.name %></div>
<div><b>Course:</b><%= @course.name %></div>
<div><b>ID:</b><%= @grade.id %></div>

<div><b>Name:</b><%= @grade.lettergrade %></div>

<div>
<%= link_to 'Edit', edit_grade_path(@grade) %> | 
<%= link_to 'Back', grades_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Student" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Student</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/studs/_form.html.erb
<%= form_for(@stud) do |f| %>

<div>
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>

<div>
<%#= f.label :grade_id %><br />
<%#= collection_select(:stud, :grade_id, Grade.all, :id, :lettergrade) %>
</div>

<div>
	<%= f.submit 'Submit' %>
</div>

<% end %>

app/views/studs/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @stud %> | 
<%= link_to 'Back', studs_path %>

app/views/studs/index.html.erb
<%= link_to 'Create New Student', new_stud_path %>

<% @studs.each do |stud| %>
<div>
	<%= stud.id %> <%= stud.name %>
	<%= link_to 'View', stud%>
	<%= link_to 'Edit', edit_stud_path(stud) %>
	<%= link_to 'Delete', stud, confirm: 'Are you sure?', method: :delete %>
</div>

<% end %>

app/views/studs/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', studs_path %>

app/views/studs/show.html.erb
<div><%= notice %></div>
<div><b>ID:</b><%= @stud.id %></div>
<div><b>Name:</b><%= @stud.name %></div>

<div><b>Grades:</b>
<% @grades.each do |grade| %>
	<%= grade.lettergrade %>
	<%
		if grade.lettergrade == "A"
			@scale = '4'
		elsif grade.lettergrade == "B"
			@scale = '3'
		elsif grade.lettergrade == "C"	
			@scale = '2'
		elsif grade.lettergrade == "D"	
			@scale = '1'
		else
			@scale = '0'
		end
	%>
	(<%= @scale %>)
<% end %>
</div>

<div><b>Courses:</b>
<% @grades.each do |grade| %>
	<%
		@course = grade.course_id
		@courseinfo = Course.find(@course)
	%>
		<%= @courseinfo.name%> (<%= @courseinfo.number %>)
<% end %>
</div>

<div>
<%= link_to 'Edit', edit_stud_path(@stud) %> | 
<%= link_to 'Back', studs_path %>
</div>